import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";

const SEED_SECRET = process.env.SEED_SECRET ?? "dev-seed-secret";

const LISTINGS_DATA = [
  // === NAPOLI (20) ===
  { title: "Trilocale luminoso in Via Toledo", description: "Appartamento luminoso al quarto piano con affaccio su Via Toledo, completamente ristrutturato nel 2023.", type: "sale" as const, property_type: "apartment" as const, price: 285000, surface_sqm: 95, rooms: 3, bathrooms: 1, floor: 4, total_floors: 6, year_built: 1960, energy_class: "D", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: true, has_elevator: true, has_cellar: true, address: "Via Toledo 234", city: "Napoli", province: "NA", zip_code: "80134", lat: 40.8438, lng: 14.2488, neighborhood: "Centro Storico", photos: [], status: "active" },
  { title: "Bilocale ristrutturato Vomero", description: "Grazioso bilocale in zona pedonale del Vomero, ideale per coppia o investimento.", type: "sale" as const, property_type: "apartment" as const, price: 220000, surface_sqm: 65, rooms: 2, bathrooms: 1, floor: 3, total_floors: 5, year_built: 1975, energy_class: "C", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: true, has_cellar: false, address: "Via Luca Giordano 78", city: "Napoli", province: "NA", zip_code: "80127", lat: 40.8542, lng: 14.2350, neighborhood: "Vomero", photos: [], status: "active" },
  { title: "Appartamento vista mare Posillipo", description: "Splendido quadrilocale con vista panoramica sul Golfo di Napoli e doppio affaccio.", type: "sale" as const, property_type: "apartment" as const, price: 520000, surface_sqm: 130, rooms: 4, bathrooms: 2, floor: 6, total_floors: 7, year_built: 1985, energy_class: "C", heating_type: "autonomo", has_parking: true, has_garden: false, has_terrace: true, has_elevator: true, has_cellar: true, address: "Via Posillipo 120", city: "Napoli", province: "NA", zip_code: "80123", lat: 40.8150, lng: 14.2000, neighborhood: "Posillipo", photos: [], status: "active" },
  { title: "Monolocale Chiaia per investimento", description: "Monolocale in pieno centro Chiaia, ottimo per affitto breve o studentesco.", type: "sale" as const, property_type: "apartment" as const, price: 152000, surface_sqm: 38, rooms: 1, bathrooms: 1, floor: 2, total_floors: 4, year_built: 1950, energy_class: "F", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: false, address: "Via Chiaia 192", city: "Napoli", province: "NA", zip_code: "80121", lat: 40.8370, lng: 14.2460, neighborhood: "Chiaia", photos: [], status: "active" },
  { title: "Quadrilocale con box Fuorigrotta", description: "Ampio appartamento in zona residenziale con posto auto coperto e cantina.", type: "sale" as const, property_type: "apartment" as const, price: 310000, surface_sqm: 120, rooms: 4, bathrooms: 2, floor: 5, total_floors: 8, year_built: 2005, energy_class: "B", heating_type: "centralizzato", has_parking: true, has_garden: false, has_terrace: true, has_elevator: true, has_cellar: true, address: "Via Giulio Cesare 45", city: "Napoli", province: "NA", zip_code: "80125", lat: 40.8270, lng: 14.1930, neighborhood: "Fuorigrotta", photos: [], status: "active" },
  { title: "Bilocale in affitto Centro Storico", description: "Bilocale arredato nel cuore del centro storico, a due passi da Spaccanapoli.", type: "rent" as const, property_type: "apartment" as const, price: 800, surface_sqm: 55, rooms: 2, bathrooms: 1, floor: 3, total_floors: 5, year_built: 1935, energy_class: "E", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: false, address: "Via San Biagio dei Librai 41", city: "Napoli", province: "NA", zip_code: "80138", lat: 40.8497, lng: 14.2570, neighborhood: "Centro Storico", photos: [], status: "active" },
  { title: "Penthouse Lungomare Napoli", description: "Attico esclusivo con terrazzo di 60 mq e vista a 180 gradi sul golfo.", type: "sale" as const, property_type: "apartment" as const, price: 890000, surface_sqm: 180, rooms: 5, bathrooms: 3, floor: 8, total_floors: 8, year_built: 2010, energy_class: "A1", heating_type: "autonomo", has_parking: true, has_garden: false, has_terrace: true, has_elevator: true, has_cellar: true, address: "Via Partenope 36", city: "Napoli", province: "NA", zip_code: "80121", lat: 40.8310, lng: 14.2480, neighborhood: "Chiaia", photos: [], status: "active" },
  { title: "Locale commerciale Via Tribunali", description: "Fondo commerciale con vetrina su strada ad alto passaggio pedonale.", type: "rent" as const, property_type: "commercial" as const, price: 1200, surface_sqm: 60, rooms: 2, bathrooms: 1, floor: 0, total_floors: 3, year_built: 1900, energy_class: "G", heating_type: "assente", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via dei Tribunali 155", city: "Napoli", province: "NA", zip_code: "80138", lat: 40.8520, lng: 14.2580, neighborhood: "Centro Storico", photos: [], status: "active" },
  { title: "Trilocale ristrutturato Pozzuoli", description: "Appartamento recentemente ristrutturato con finiture di pregio, vicino al Rione Terra.", type: "sale" as const, property_type: "apartment" as const, price: 195000, surface_sqm: 85, rooms: 3, bathrooms: 1, floor: 2, total_floors: 4, year_built: 1988, energy_class: "D", heating_type: "autonomo", has_parking: true, has_garden: false, has_terrace: true, has_elevator: false, has_cellar: false, address: "Via Napoli 102", city: "Pozzuoli", province: "NA", zip_code: "80078", lat: 40.8233, lng: 14.1230, neighborhood: "Centro", photos: [], status: "active" },
  { title: "Appartamento Secondigliano con terrazzo", description: "Quadrilocale con ampio terrazzo vivibile, ottimo per famiglie numerose.", type: "sale" as const, property_type: "apartment" as const, price: 145000, surface_sqm: 100, rooms: 4, bathrooms: 1, floor: 3, total_floors: 5, year_built: 1978, energy_class: "E", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: true, has_elevator: false, has_cellar: true, address: "Corso Secondigliano 198", city: "Napoli", province: "NA", zip_code: "80144", lat: 40.8870, lng: 14.2660, neighborhood: "Secondigliano", photos: [], status: "sold" },
  { title: "Villa panoramica Posillipo", description: "Villa indipendente con giardino e accesso privato al mare, posizione unica.", type: "sale" as const, property_type: "villa" as const, price: 1450000, surface_sqm: 320, rooms: 7, bathrooms: 4, floor: 0, total_floors: 3, year_built: 1955, energy_class: "D", heating_type: "autonomo", has_parking: true, has_garden: true, has_terrace: true, has_elevator: false, has_cellar: true, address: "Via Ferdinando Russo 18", city: "Napoli", province: "NA", zip_code: "80123", lat: 40.8090, lng: 14.1920, neighborhood: "Posillipo", photos: [], status: "active" },
  { title: "Trilocale nuovo Bagnoli", description: "Appartamento di nuova costruzione in complesso residenziale con area verde condominiale.", type: "sale" as const, property_type: "apartment" as const, price: 265000, surface_sqm: 82, rooms: 3, bathrooms: 2, floor: 2, total_floors: 5, year_built: 2024, energy_class: "A2", heating_type: "autonomo", has_parking: true, has_garden: false, has_terrace: true, has_elevator: true, has_cellar: true, address: "Via Coroglio 54", city: "Napoli", province: "NA", zip_code: "80124", lat: 40.8110, lng: 14.1670, neighborhood: "Bagnoli", photos: [], status: "active" },
  { title: "Bilocale arredato Vomero in affitto", description: "Bilocale completamente arredato e climatizzato, pronto per essere abitato.", type: "rent" as const, property_type: "apartment" as const, price: 900, surface_sqm: 52, rooms: 2, bathrooms: 1, floor: 4, total_floors: 6, year_built: 1968, energy_class: "D", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: true, has_cellar: false, address: "Via Bernini 64", city: "Napoli", province: "NA", zip_code: "80129", lat: 40.8520, lng: 14.2290, neighborhood: "Vomero", photos: [], status: "rented" },
  { title: "Negozio con soppalco Chiaia", description: "Locale commerciale su due livelli in via ad alto passaggio, ideale per boutique.", type: "sale" as const, property_type: "commercial" as const, price: 320000, surface_sqm: 75, rooms: 2, bathrooms: 1, floor: 0, total_floors: 1, year_built: 1930, energy_class: "G", heating_type: "assente", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via dei Mille 35", city: "Napoli", province: "NA", zip_code: "80121", lat: 40.8390, lng: 14.2420, neighborhood: "Chiaia", photos: [], status: "active" },
  { title: "Appartamento da ristrutturare Centro Storico", description: "Ampio appartamento d'epoca con soffitti a volta e affreschi, da ristrutturare completamente.", type: "sale" as const, property_type: "apartment" as const, price: 180000, surface_sqm: 110, rooms: 4, bathrooms: 1, floor: 1, total_floors: 4, year_built: 1920, energy_class: "G", heating_type: "assente", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via San Gregorio Armeno 28", city: "Napoli", province: "NA", zip_code: "80138", lat: 40.8505, lng: 14.2590, neighborhood: "Centro Storico", photos: [], status: "active" },
  { title: "Trilocale moderno Fuorigrotta", description: "Appartamento moderno vicino alla metropolitana e allo stadio Maradona.", type: "rent" as const, property_type: "apartment" as const, price: 850, surface_sqm: 78, rooms: 3, bathrooms: 1, floor: 6, total_floors: 8, year_built: 2002, energy_class: "C", heating_type: "centralizzato", has_parking: true, has_garden: false, has_terrace: false, has_elevator: true, has_cellar: false, address: "Via Leopardi 12", city: "Napoli", province: "NA", zip_code: "80125", lat: 40.8260, lng: 14.1880, neighborhood: "Fuorigrotta", photos: [], status: "active" },
  { title: "Bilocale venduto Pozzuoli mare", description: "Bilocale con vista sul porto di Pozzuoli, recentemente venduto.", type: "sale" as const, property_type: "apartment" as const, price: 168000, surface_sqm: 58, rooms: 2, bathrooms: 1, floor: 4, total_floors: 5, year_built: 1992, energy_class: "D", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: true, has_elevator: true, has_cellar: false, address: "Via Sacchini 15", city: "Pozzuoli", province: "NA", zip_code: "80078", lat: 40.8250, lng: 14.1200, neighborhood: "Porto", photos: [], status: "sold" },
  { title: "Quadrilocale Secondigliano economia", description: "Appartamento spazioso a prezzo accessibile, ben collegato con metropolitana.", type: "sale" as const, property_type: "apartment" as const, price: 125000, surface_sqm: 95, rooms: 4, bathrooms: 1, floor: 1, total_floors: 4, year_built: 1982, energy_class: "F", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via del Cassano 77", city: "Napoli", province: "NA", zip_code: "80144", lat: 40.8900, lng: 14.2620, neighborhood: "Secondigliano", photos: [], status: "active" },
  { title: "Ufficio commerciale Bagnoli", description: "Ufficio open space con due sale riunioni, zona ex Italsider in piena riqualificazione.", type: "rent" as const, property_type: "commercial" as const, price: 1500, surface_sqm: 120, rooms: 4, bathrooms: 2, floor: 1, total_floors: 3, year_built: 2018, energy_class: "B", heating_type: "centralizzato", has_parking: true, has_garden: false, has_terrace: false, has_elevator: true, has_cellar: false, address: "Via Diocleziano 270", city: "Napoli", province: "NA", zip_code: "80124", lat: 40.8140, lng: 14.1750, neighborhood: "Bagnoli", photos: [], status: "active" },
  { title: "Attico con roof garden Chiaia", description: "Esclusivo attico con roof garden privato e vista su Castel dell'Ovo.", type: "sale" as const, property_type: "apartment" as const, price: 750000, surface_sqm: 160, rooms: 4, bathrooms: 2, floor: 7, total_floors: 7, year_built: 2016, energy_class: "A3", heating_type: "autonomo", has_parking: true, has_garden: true, has_terrace: true, has_elevator: true, has_cellar: true, address: "Via Crispi 86", city: "Napoli", province: "NA", zip_code: "80121", lat: 40.8350, lng: 14.2400, neighborhood: "Chiaia", photos: [], status: "active" },

  // === CASERTA E PROVINCIA (10) ===
  { title: "Villa con giardino Caserta Vecchia", description: "Villa su due livelli con ampio giardino e vista sulla Reggia di Caserta.", type: "sale" as const, property_type: "villa" as const, price: 380000, surface_sqm: 200, rooms: 5, bathrooms: 3, floor: 0, total_floors: 2, year_built: 1990, energy_class: "D", heating_type: "autonomo", has_parking: true, has_garden: true, has_terrace: true, has_elevator: false, has_cellar: true, address: "Via Caserta Vecchia 15", city: "Caserta", province: "CE", zip_code: "81100", lat: 41.0882, lng: 14.3260, neighborhood: "Caserta Vecchia", photos: [], status: "active" },
  { title: "Trilocale nuovo Caserta centro", description: "Appartamento di nuova costruzione in classe A2, zona centralissima vicino alla Reggia.", type: "sale" as const, property_type: "apartment" as const, price: 195000, surface_sqm: 85, rooms: 3, bathrooms: 1, floor: 2, total_floors: 4, year_built: 2022, energy_class: "A2", heating_type: "autonomo", has_parking: true, has_garden: false, has_terrace: true, has_elevator: true, has_cellar: true, address: "Corso Trieste 88", city: "Caserta", province: "CE", zip_code: "81100", lat: 41.0725, lng: 14.3331, neighborhood: "Centro", photos: [], status: "active" },
  { title: "Appartamento Aversa zona universita", description: "Trilocale in affitto vicino alla facolta di Ingegneria, ideale per studenti.", type: "rent" as const, property_type: "apartment" as const, price: 550, surface_sqm: 70, rooms: 3, bathrooms: 1, floor: 1, total_floors: 3, year_built: 1980, energy_class: "E", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: false, address: "Via Roma 56", city: "Aversa", province: "CE", zip_code: "81031", lat: 40.9730, lng: 14.2080, neighborhood: "Centro", photos: [], status: "active" },
  { title: "Bilocale economico Maddaloni", description: "Bilocale al piano terra con ingresso indipendente, perfetto come primo acquisto.", type: "sale" as const, property_type: "apartment" as const, price: 72000, surface_sqm: 55, rooms: 2, bathrooms: 1, floor: 0, total_floors: 3, year_built: 1970, energy_class: "F", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via San Francesco d'Assisi 12", city: "Maddaloni", province: "CE", zip_code: "81024", lat: 41.0380, lng: 14.3830, neighborhood: "Centro", photos: [], status: "active" },
  { title: "Casa indipendente Santa Maria CV", description: "Casa su due livelli con cortile interno nel centro storico di Santa Maria Capua Vetere.", type: "sale" as const, property_type: "house" as const, price: 165000, surface_sqm: 140, rooms: 4, bathrooms: 2, floor: 0, total_floors: 2, year_built: 1965, energy_class: "E", heating_type: "autonomo", has_parking: true, has_garden: true, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via Mazzocchi 44", city: "Santa Maria Capua Vetere", province: "CE", zip_code: "81055", lat: 41.0820, lng: 14.2580, neighborhood: "Centro Storico", photos: [], status: "sold" },
  { title: "Quadrilocale panoramico Caserta", description: "Appartamento al quinto piano con vista sulla Reggia e sui monti Tifatini.", type: "sale" as const, property_type: "apartment" as const, price: 230000, surface_sqm: 110, rooms: 4, bathrooms: 2, floor: 5, total_floors: 6, year_built: 1998, energy_class: "C", heating_type: "centralizzato", has_parking: true, has_garden: false, has_terrace: true, has_elevator: true, has_cellar: true, address: "Viale Carlo III 120", city: "Caserta", province: "CE", zip_code: "81100", lat: 41.0760, lng: 14.3280, neighborhood: "Centro", photos: [], status: "active" },
  { title: "Locale commerciale Aversa centro", description: "Ampio fondo commerciale su strada principale con grande vetrina.", type: "sale" as const, property_type: "commercial" as const, price: 145000, surface_sqm: 80, rooms: 2, bathrooms: 1, floor: 0, total_floors: 1, year_built: 1958, energy_class: "G", heating_type: "assente", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: true, address: "Piazza Municipio 8", city: "Aversa", province: "CE", zip_code: "81031", lat: 40.9740, lng: 14.2070, neighborhood: "Centro", photos: [], status: "active" },
  { title: "Villa bifamiliare Caserta sud", description: "Porzione di villa bifamiliare con giardino privato e doppio garage.", type: "sale" as const, property_type: "villa" as const, price: 295000, surface_sqm: 170, rooms: 5, bathrooms: 2, floor: 0, total_floors: 2, year_built: 2008, energy_class: "B", heating_type: "autonomo", has_parking: true, has_garden: true, has_terrace: true, has_elevator: false, has_cellar: true, address: "Via Tifatina 22", city: "Caserta", province: "CE", zip_code: "81100", lat: 41.0650, lng: 14.3400, neighborhood: "San Clemente", photos: [], status: "active" },
  { title: "Monolocale Maddaloni in affitto", description: "Monolocale arredato adatto a singolo lavoratore o studente pendolare.", type: "rent" as const, property_type: "apartment" as const, price: 350, surface_sqm: 35, rooms: 1, bathrooms: 1, floor: 2, total_floors: 4, year_built: 1985, energy_class: "E", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: false, address: "Via Roma 88", city: "Maddaloni", province: "CE", zip_code: "81024", lat: 41.0370, lng: 14.3810, neighborhood: "Centro", photos: [], status: "rented" },
  { title: "Trilocale Santa Maria Capua Vetere", description: "Trilocale luminoso vicino all'Anfiteatro Campano, ristrutturato nel 2020.", type: "sale" as const, property_type: "apartment" as const, price: 128000, surface_sqm: 80, rooms: 3, bathrooms: 1, floor: 3, total_floors: 4, year_built: 1976, energy_class: "D", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: true, has_elevator: false, has_cellar: false, address: "Via Galatina 30", city: "Santa Maria Capua Vetere", province: "CE", zip_code: "81055", lat: 41.0810, lng: 14.2560, neighborhood: "Centro", photos: [], status: "active" },

  // === SALERNO E PROVINCIA (10) ===
  { title: "Loft moderno Salerno centro", description: "Loft open space con finiture contemporanee nel cuore del centro storico salernitano.", type: "sale" as const, property_type: "apartment" as const, price: 245000, surface_sqm: 80, rooms: 2, bathrooms: 1, floor: 3, total_floors: 4, year_built: 2018, energy_class: "A3", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: true, has_elevator: true, has_cellar: false, address: "Via dei Mercanti 22", city: "Salerno", province: "SA", zip_code: "84121", lat: 40.6824, lng: 14.7681, neighborhood: "Centro Storico", photos: [], status: "active" },
  { title: "Villa bifamiliare Cava de' Tirreni", description: "Porzione di villa con ingresso indipendente e giardino, zona collinare tranquilla.", type: "sale" as const, property_type: "house" as const, price: 340000, surface_sqm: 180, rooms: 5, bathrooms: 2, floor: 0, total_floors: 2, year_built: 2000, energy_class: "C", heating_type: "autonomo", has_parking: true, has_garden: true, has_terrace: true, has_elevator: false, has_cellar: true, address: "Via XXV Luglio 33", city: "Cava de' Tirreni", province: "SA", zip_code: "84013", lat: 40.7000, lng: 14.7060, neighborhood: "Centro", photos: [], status: "active" },
  { title: "Bilocale vista mare Amalfi", description: "Bilocale caratteristico con terrazzino vista mare sulla Costiera Amalfitana.", type: "sale" as const, property_type: "apartment" as const, price: 420000, surface_sqm: 55, rooms: 2, bathrooms: 1, floor: 2, total_floors: 3, year_built: 1970, energy_class: "E", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: true, has_elevator: false, has_cellar: false, address: "Via Lorenzo d'Amalfi 8", city: "Amalfi", province: "SA", zip_code: "84011", lat: 40.6340, lng: 14.6027, neighborhood: "Centro", photos: [], status: "active" },
  { title: "Attico con terrazzo Salerno mare", description: "Attico di pregio sul lungomare di Salerno con terrazzo panoramico e doppi servizi.", type: "sale" as const, property_type: "apartment" as const, price: 375000, surface_sqm: 110, rooms: 3, bathrooms: 2, floor: 5, total_floors: 5, year_built: 2015, energy_class: "A2", heating_type: "autonomo", has_parking: true, has_garden: false, has_terrace: true, has_elevator: true, has_cellar: true, address: "Lungomare Trieste 45", city: "Salerno", province: "SA", zip_code: "84121", lat: 40.6750, lng: 14.7710, neighborhood: "Lungomare", photos: [], status: "active" },
  { title: "Bilocale studenti Fisciano", description: "Bilocale arredato vicino al campus universitario di Fisciano, affitto tutto incluso.", type: "rent" as const, property_type: "apartment" as const, price: 450, surface_sqm: 50, rooms: 2, bathrooms: 1, floor: 1, total_floors: 3, year_built: 2000, energy_class: "D", heating_type: "autonomo", has_parking: true, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: false, address: "Via Università 18", city: "Fisciano", province: "SA", zip_code: "84084", lat: 40.7740, lng: 14.7890, neighborhood: "Universita", photos: [], status: "active" },
  { title: "Trilocale Battipaglia zona stazione", description: "Appartamento comodo vicino alla stazione ferroviaria, ideale per pendolari.", type: "rent" as const, property_type: "apartment" as const, price: 600, surface_sqm: 75, rooms: 3, bathrooms: 1, floor: 2, total_floors: 4, year_built: 1990, energy_class: "D", heating_type: "autonomo", has_parking: true, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via Italia 66", city: "Battipaglia", province: "SA", zip_code: "84091", lat: 40.6090, lng: 14.9840, neighborhood: "Stazione", photos: [], status: "rented" },
  { title: "Casa colonica ristrutturata Cava", description: "Antica casa colonica completamente ristrutturata con giardino e forno a legna.", type: "sale" as const, property_type: "house" as const, price: 280000, surface_sqm: 160, rooms: 4, bathrooms: 2, floor: 0, total_floors: 2, year_built: 1940, energy_class: "D", heating_type: "autonomo", has_parking: true, has_garden: true, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via Filangieri 5", city: "Cava de' Tirreni", province: "SA", zip_code: "84013", lat: 40.6980, lng: 14.7100, neighborhood: "Corpo di Cava", photos: [], status: "sold" },
  { title: "Appartamento venduto Amalfi centro", description: "Trilocale nel borgo antico di Amalfi, venduto nel 2025.", type: "sale" as const, property_type: "apartment" as const, price: 510000, surface_sqm: 70, rooms: 3, bathrooms: 1, floor: 1, total_floors: 3, year_built: 1960, energy_class: "F", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: true, has_elevator: false, has_cellar: false, address: "Piazza Duomo 3", city: "Amalfi", province: "SA", zip_code: "84011", lat: 40.6345, lng: 14.6020, neighborhood: "Centro", photos: [], status: "sold" },
  { title: "Deposito commerciale Battipaglia", description: "Ampio deposito con accesso carraio, zona industriale ben collegata all'autostrada.", type: "sale" as const, property_type: "commercial" as const, price: 180000, surface_sqm: 250, rooms: 1, bathrooms: 1, floor: 0, total_floors: 1, year_built: 2005, energy_class: "G", heating_type: "assente", has_parking: true, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: false, address: "Via Spineta zona ASI", city: "Battipaglia", province: "SA", zip_code: "84091", lat: 40.6050, lng: 14.9900, neighborhood: "Zona Industriale", photos: [], status: "active" },
  { title: "Monolocale Fisciano affitto studenti", description: "Monolocale essenziale e funzionale per studenti dell'Universita di Salerno.", type: "rent" as const, property_type: "apartment" as const, price: 320, surface_sqm: 30, rooms: 1, bathrooms: 1, floor: 0, total_floors: 2, year_built: 1995, energy_class: "E", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: false, address: "Via Ponte Don Melillo 4", city: "Fisciano", province: "SA", zip_code: "84084", lat: 40.7750, lng: 14.7870, neighborhood: "Lancusi", photos: [], status: "rented" },

  // === AVELLINO E BENEVENTO (10) ===
  { title: "Trilocale panoramico Avellino", description: "Appartamento con splendida vista sui monti Picentini, zona tranquilla e servita.", type: "sale" as const, property_type: "apartment" as const, price: 145000, surface_sqm: 90, rooms: 3, bathrooms: 1, floor: 5, total_floors: 6, year_built: 1985, energy_class: "E", heating_type: "autonomo", has_parking: true, has_garden: false, has_terrace: false, has_elevator: true, has_cellar: true, address: "Corso Vittorio Emanuele 112", city: "Avellino", province: "AV", zip_code: "83100", lat: 40.9140, lng: 14.7906, neighborhood: "Centro", photos: [], status: "active" },
  { title: "Casa indipendente Ariano Irpino", description: "Casa su due livelli con terreno agricolo annesso, panorama sulla valle dell'Ufita.", type: "sale" as const, property_type: "house" as const, price: 120000, surface_sqm: 150, rooms: 4, bathrooms: 2, floor: 0, total_floors: 2, year_built: 1975, energy_class: "F", heating_type: "autonomo", has_parking: true, has_garden: true, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via Cardito 25", city: "Ariano Irpino", province: "AV", zip_code: "83031", lat: 41.1530, lng: 15.0880, neighborhood: "Cardito", photos: [], status: "active" },
  { title: "Rustico da ristrutturare Montella", description: "Casale in pietra con 2000 mq di terreno, da ristrutturare completamente.", type: "sale" as const, property_type: "house" as const, price: 65000, surface_sqm: 120, rooms: 4, bathrooms: 1, floor: 0, total_floors: 2, year_built: 1940, energy_class: "G", heating_type: "assente", has_parking: true, has_garden: true, has_terrace: false, has_elevator: false, has_cellar: true, address: "Contrada San Marco 5", city: "Montella", province: "AV", zip_code: "83048", lat: 40.8450, lng: 15.0170, neighborhood: "Contrada San Marco", photos: [], status: "active" },
  { title: "Appartamento centro storico Benevento", description: "Trilocale nel cuore di Benevento, a pochi passi dall'Arco di Traiano.", type: "sale" as const, property_type: "apartment" as const, price: 115000, surface_sqm: 85, rooms: 3, bathrooms: 1, floor: 2, total_floors: 4, year_built: 1962, energy_class: "E", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: false, has_cellar: true, address: "Corso Garibaldi 78", city: "Benevento", province: "BN", zip_code: "82100", lat: 41.1297, lng: 14.7826, neighborhood: "Centro Storico", photos: [], status: "active" },
  { title: "Villa moderna Benevento collina", description: "Villa di recente costruzione con piscina e vista panoramica sulla citta.", type: "sale" as const, property_type: "villa" as const, price: 350000, surface_sqm: 220, rooms: 6, bathrooms: 3, floor: 0, total_floors: 2, year_built: 2019, energy_class: "A1", heating_type: "autonomo", has_parking: true, has_garden: true, has_terrace: true, has_elevator: false, has_cellar: true, address: "Contrada Olivola 12", city: "Benevento", province: "BN", zip_code: "82100", lat: 41.1250, lng: 14.7750, neighborhood: "Contrada Olivola", photos: [], status: "active" },
  { title: "Bilocale Avellino in affitto", description: "Bilocale arredato in centro Avellino, comodo a tutti i servizi.", type: "rent" as const, property_type: "apartment" as const, price: 420, surface_sqm: 50, rooms: 2, bathrooms: 1, floor: 3, total_floors: 5, year_built: 1988, energy_class: "D", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: true, has_cellar: false, address: "Via Tagliamento 19", city: "Avellino", province: "AV", zip_code: "83100", lat: 40.9160, lng: 14.7950, neighborhood: "Centro", photos: [], status: "rented" },
  { title: "Quadrilocale Sant'Agata de' Goti", description: "Appartamento nel borgo medievale con vista sulla valle, finiture d'epoca.", type: "sale" as const, property_type: "apartment" as const, price: 98000, surface_sqm: 100, rooms: 4, bathrooms: 1, floor: 1, total_floors: 3, year_built: 1945, energy_class: "F", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: true, has_elevator: false, has_cellar: true, address: "Via Roma 14", city: "Sant'Agata de' Goti", province: "BN", zip_code: "82019", lat: 41.0900, lng: 14.5010, neighborhood: "Centro Storico", photos: [], status: "active" },
  { title: "Casa con terreno Montella", description: "Casetta indipendente con 5000 mq di castagneto, zona turistica del Terminio.", type: "sale" as const, property_type: "house" as const, price: 95000, surface_sqm: 100, rooms: 3, bathrooms: 1, floor: 0, total_floors: 1, year_built: 1955, energy_class: "G", heating_type: "autonomo", has_parking: true, has_garden: true, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via Verteglia 8", city: "Montella", province: "AV", zip_code: "83048", lat: 40.8430, lng: 15.0200, neighborhood: "Verteglia", photos: [], status: "active" },
  { title: "Trilocale Benevento zona stazione", description: "Appartamento ben collegato vicino alla stazione centrale di Benevento.", type: "sale" as const, property_type: "apartment" as const, price: 105000, surface_sqm: 78, rooms: 3, bathrooms: 1, floor: 4, total_floors: 5, year_built: 1980, energy_class: "E", heating_type: "autonomo", has_parking: false, has_garden: false, has_terrace: false, has_elevator: true, has_cellar: false, address: "Viale Principe di Napoli 55", city: "Benevento", province: "BN", zip_code: "82100", lat: 41.1310, lng: 14.7870, neighborhood: "Ferrovia", photos: [], status: "active" },
  { title: "Palazzo storico Ariano Irpino", description: "Porzione di palazzo nobiliare con affreschi e soffitti decorati, da restaurare parzialmente.", type: "sale" as const, property_type: "house" as const, price: 85000, surface_sqm: 200, rooms: 6, bathrooms: 2, floor: 0, total_floors: 3, year_built: 1920, energy_class: "G", heating_type: "assente", has_parking: false, has_garden: true, has_terrace: false, has_elevator: false, has_cellar: true, address: "Via Tribunali 6", city: "Ariano Irpino", province: "AV", zip_code: "83031", lat: 41.1520, lng: 15.0860, neighborhood: "Centro Storico", photos: [], status: "active" },
];

// GET senza auth per seed facile dal browser
export async function GET() {
  if (process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: "Seed disabilitato in produzione" }, { status: 403 });
  }
  return runSeed();
}

export async function POST(request: NextRequest) {
  // Check authorization
  const isDev = process.env.NODE_ENV === "development";
  const authHeader = request.headers.get("authorization");
  const secretMatch = authHeader === `Bearer ${SEED_SECRET}`;

  if (!isDev && !secretMatch) {
    return NextResponse.json(
      { error: "Non autorizzato. Usa header Authorization: Bearer <secret> oppure esegui in development." },
      { status: 401 }
    );
  }

  return runSeed();
}

async function runSeed() {
  const supabase = createAdminClient();

  // Create a placeholder embedding (1536 zeros)
  const zeroEmbedding = `[${new Array(1536).fill(0).join(",")}]`;

  const listingsWithEmbeddings = LISTINGS_DATA.map((listing) => ({
    ...listing,
    price_period: listing.type === "rent" ? "month" : null,
    embedding: zeroEmbedding,
    views_count: Math.floor(Math.random() * 500),
    is_featured: Math.random() > 0.8,
  }));

  const { data, error } = await supabase
    .from("listings")
    .insert(listingsWithEmbeddings)
    .select("id, title, city");

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({
    message: `Seed completato: ${data.length} annunci inseriti.`,
    listings: data,
  });
}
